apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kindest
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kindest
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kindest
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
      serviceAccountName: {{ .Release.Name }}-kindest
      containers:
        - name: kindest
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          image: {{ .Values.image }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
{{ toYaml .Values.resources | indent 12 }}
